apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: developement
  labels:
    app: nginx
    svc: test-nginx
spec:
  selector:
  type: ClusterIP
    app: nginx
  ports:
   - protocol: TCP
    port: 8080
    targetPort: 80
